export const crOptions = [
  { label: '0', value: 0.0 },
  { label: '1/8', value: 0.125 },
  { label: '1/4', value: 0.25 },
  { label: '1/2', value: 0.5 },
  { label: '1', value: 1.0 },
  { label: '2', value: 2.0 },
  { label: '3', value: 3.0 },
  { label: '4', value: 4.0 },
  { label: '5', value: 5.0 },
  { label: '6', value: 6.0 },
  { label: '7', value: 7.0 },
  { label: '8', value: 8.0 },
  { label: '9', value: 9.0 },
  { label: '10', value: 10.0 },
  { label: '11', value: 11.0 },
  { label: '12', value: 12.0 },
  { label: '13', value: 13.0 },
  { label: '14', value: 14.0 },
  { label: '15', value: 15.0 },
  { label: '16', value: 16.0 },
  { label: '17', value: 17.0 },
  { label: '18', value: 18.0 },
  { label: '19', value: 19.0 },
  { label: '20', value: 20.0 },
  { label: '21', value: 21.0 },
  { label: '22', value: 22.0 },
  { label: '23', value: 23.0 },
  { label: '24', value: 24.0 },
  { label: '30', value: 30.0 },
]

export const abilities = ['STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA']

export const initiativeKeys = [
  'ac',
  'campaign',
  'concentration',
  'conditions',
  'created_at',
  'deathSaves',
  'health',
  'id',
  'index',
  'initiative',
  'initiative_modifier',
  'link',
  'maxAc',
  'maxHealth',
  'maxAcOld',
  'maxHealthOld',
  'name',
  'note',
  'tempAc',
  'tempHealth',
  'type',
  'summoner',
  'actions',
  'legendary_actions',
  'reactions',
  'special_abilities',
]
