export const playgroundSheet: InitiativeSheet = {
  id: 1,
  createdAt: '2022-12-07T07:34:18+00:00',
  createdBy: 'me :)',
  title: 'Playground',
  round: 1,
  activeIndex: 0,
  rows: [],
  info: null,
  infoCards: [],
  settings: {
    spacing: 'normal',
    pet: 'cat',
    rows: [
      'armorClass',
      'hitPoints',
      'conditions',
      'note',
      'deathSaves',
      'concentration',
      'modify',
    ],
    modified: false,
    negative: false,
  },
}
