import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { format, resolveConfig } from 'prettier'
import { buildStyleOptions } from '~~/server/utils/avatar-style'
import { getErrorMessage } from '~~/shared/utils/errors'

const target = resolve(import.meta.dirname, '../constants/avatar-options.ts')

const header = `// Generated by \`npm run avatar:options\` — do not edit by hand.
import type { ConfigStyleOptions } from '~~/shared/types/avatar'

export const avatarStyleOptions: ConfigStyleOptions = `

async function main(): Promise<void> {
  const options = buildStyleOptions()
  const config = await resolveConfig(target)
  const source = await format(`${header}${JSON.stringify(options)}`, {
    ...config,
    filepath: target,
  })

  await writeFile(target, source)

  const keys = Object.keys(options)

  console.info(`wrote ${keys.length} option(s) to constants/avatar-options.ts`)
  console.info(keys.map(key => `  ${key}`).join('\n'))
}

main().catch((error: unknown) => {
  console.error(getErrorMessage(error))
  process.exitCode = 1
})
